spring:
  data:
    elasticsearch:
      cluster-name: ${shishi-social.elasticsearch.cluster-name}
      cluster-nodes: ${shishi-social.elasticsearch.cluster-nodes}
      repositories:
        enabled: true

shishi-social:
  swagger:
    enabled: true
    title: 日志中心
    description: 日志中心接口文档
    version: 1.0
    base-package: com.shishi.log.controller